import type { NextPage } from 'next'
import React, { useState } from 'react'
import Head from 'next/head'
import { PrefectureList } from '../components/PrefectureList'
import { PrefPopulations } from '../types/prefPopulations'
import { Chart } from '../components/Chart'

const Home: NextPage = () => {
  const [prefPopulations, setPrefPopulations] = useState<PrefPopulations[]>([])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script src='https://cdn.tailwindcss.com'></script>
      </Head>

      <main>
        <PrefectureList
          prefPopulations={prefPopulations}
          setPrefPopulations={setPrefPopulations}
        />

        <Chart prefPopulations={prefPopulations} />
      </main>
      <footer></footer>
    </div>
  )
}

export default Home
