import type { NextPage } from 'next'
import Link from 'next/link'
import React, { useState, useEffect, useCallback } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Highcharts from 'highcharts'
import HighchartsExporting from 'highcharts/modules/exporting'
import HighchartsReact from 'highcharts-react-official'

interface Prefectures {
  prefCode: number
  prefName: string
}

interface PrefPopulation {
  year: number
  value: number
}

const Home: NextPage = () => {
  // 都道府県名
  const [prefectures, setPrefectures] = useState<Prefectures[]>([])
  // 選択する都道府県
  // ["1", "13", "42"]とかにする
  const [choosePref, setChoosePref] = useState<String[]>([])

  // 選択した都道府県の人口データ
  const [prefPopulation, setPrefPopulation] = useState<PrefPopulation[]>([])

  // 都道府県名を取得
  useEffect(() => {
    fetch('https://opendata.resas-portal.go.jp/api/v1/prefectures', {
      headers: { 'X-API-KEY': String(process.env.NEXT_PUBLIC_RESAS_APIKEY) },
    })
      .then((res) => res.json())
      .then((res) => {
        setPrefectures(res.result)
      })
  }, [])
  // console.log(prefectures[0].prefCode)

  const addPrefecture = (number: string) => {
    setChoosePref([...choosePref, number])
  }
  // 選択した都道府県のデータを取得
  useEffect(() => {
    if (choosePref[0]) {
      fetch(
        `https://opendata.resas-portal.go.jp/api/v1/population/composition/perYear?cityCode=-&prefCode=${choosePref[0]}`,
        {
          headers: {
            'X-API-KEY': String(process.env.NEXT_PUBLIC_RESAS_APIKEY),
          },
        }
      )
        .then((res) => res.json())
        .then((res) => {
          setPrefPopulation(res.result.data[0].data)
        })
    }
  }, [choosePref])

  console.log(choosePref)
  // console.log(prefPopulation)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <script src='https://cdn.tailwindcss.com'></script>
      </Head>

      <main>
        <ul className='flex flex-wrap gap-4'>
          {prefectures &&
            prefectures.map((v, i) => (
              <li
                className='flex items-center'
                key={i}
                // onClick={() => setChoosePref(String(v.prefCode))}
                onChange={() => addPrefecture(String(v.prefCode))}
              >
                <input type='checkbox' name='' id={v.prefName} />
                <label htmlFor={v.prefName}>
                  {v.prefCode}. {v.prefName}
                </label>
              </li>
            ))}
        </ul>

        <ul className='flex gap-4'>
          {choosePref &&
            prefPopulation &&
            prefPopulation.map((v, i) => (
              <li key={i}>
                {v.year}: {v.value}
              </li>
              // <div key={i}>
              //   {v.map((value, index) => (
              //     <li key={index}>
              //       {value.year}: {value.value}
              //     </li>
              //   ))}
              // </div>
            ))}
        </ul>
      </main>
      <footer></footer>
    </div>
  )
}

export default Home
