import Head from 'next/head'
import { FC, ReactNode } from 'react'

interface Props {
  children: ReactNode
}

export const Layout: FC<Props> = ({ children }) => {
  return (
    <div className='pb-[50px] min-h-screen w-full overflow-hidden text-[20px]'>
      <div className=''>
        <Head>
          <title>Population Composition of Prefectures</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <script src='https://cdn.tailwindcss.com'></script>
        </Head>

        <header className='w-full bg-gray-300 p-4 text-center text-[25px] font-mono'>
          人口構成グラフ
        </header>

        <main className='max-w-[780px] mx-4 md:mx-auto mt-10'>{children}</main>
      </div>
    </div>
  )
}
