import Head from 'next/head'
import { FC, ReactNode } from 'react'

interface Props {
  children: ReactNode
}

export const Layout: FC<Props> = ({ children }) => {
  return (
    <div className='layout'>
      <Head>
        <title>Population Composition of Prefectures</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        {/* <script src='https://cdn.tailwindcss.com'></script> */}
      </Head>

      <div>
        <header>人口構成グラフ</header>
        <main>{children}</main>
      </div>
    </div>
  )
}
